### ISSUE TITLE
Upgrade to FontAwesome 5

### ISSUE THREAD

**Issue by jacobvenable** [PurdueMarketingAndMedia/purdueTemplates-2015#86]
I'd like to put upgrading from [FontAwesome 4](https://fontawesome.com/v4.7.0/) to [Fontawesome 5](https://fontawesome.com/) on our list. After contacting them, they let us know that the Pro version pricing isn't really setup for content management systems, but they are looking into changing their pricing model. In the meantime, we can implement the free version.

## TODO

The following list based on their [upgrade docs](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4).

- [ ] remove version 4 assets and references
- [ ] add FontAwesome 5 SVG script (I recommend taking advantage of they're [CDN](https://fontawesome.com/start))
- [ ] implement [upgrade Shim](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#shims) (these will eventually be removed once we're confident every icon class has been properly updated)
- [ ] update any `font-family:FontAwesome` to `font-family:"Font Awesome 5 Free"`
